image: docker
services:
    - docker:dind
stages:
    - test
test:
    stage: test
    only: 
        - master
    script:
        - echo "Player App"
        - docker --version
        - docker-compose --version
        - cd app/ && docker-compose -f docker-compose.prod.yml up --build
        - sudo docker rmi $(sudo docker images -f "dangling=true" -q)
