image: tmaier/docker-compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version

build image:
  stage: build
  script:
    - docker-compose -f docker-compose.prod.yml up --build
    - sudo docker rmi $(sudo docker images -f "dangling=true" -q)
