version: "3"

services:
  mongo1:
    hostname: mongo
    container_name: localmongo
    image: mongo:4.4
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes: 
      - mongodb:/data/db
    restart: always
volumes:
  mongodb: