version: "3.4"

services:
    node-server:
        build:
            context: .
            args:
                NODE_ENV: production
        container_name: node-server
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        volumes:
            - ./src:/app/src
            - .env:/app/.env
            - ./logs:/app/logs
        restart: always
    # mongodb:
    #     image: mongo:4.2
    #     ports:
    #         - "27017:27017"
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    #         - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    #     volumes:
    #         - mongodb-data:/data/db
    #     restart: always
volumes:
    logs: