const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}
const OPERATIONS = {
    PLUS: "+",
    SUBTRACT: "-"
}
const ACTIONS = {
    RECEIVE_MONEY_DONATE: "RECEIVE_MONEY_DONATE",
    DONATE: "DONATE",
    RENT_PLAYER: "RENT_PLAYER",
    RECEIVE_MONEY_HIRE: "RECEIVE_MONEY_HIRE",
    CANCEL_HIRE: "CANCEL_HIRE",
    RECHARGE: "RECHARGE"
}
const COLLECTION_NAME = "balance_fluctuations"
const SUCCESS_CODES = {
    CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
    GET_BALANCE_FLUCTUATIONS_SUCCESS: "GET_BALANCE_FLUCTUATIONS_SUCCESS",
    GET_DETAIL_REVIEW_SUCCESS: "GET_DETAIL_REVIEW_SUCCESS",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    UPDATE_REVIEW_SUCCESS: "UPDATE_REVIEW_SUCCESS"
}

const ERROR_CODES = {
    ERROR_REVIEW_NOT_FOUND: "ERROR_REVIEW_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND"
}

export default { COLLECTION_NAME, STATUS, SUCCESS_CODES, ERROR_CODES, ACTIONS, OPERATIONS }
