const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}

const TYPES = {
    PRIVATE: 1,
    PUBLIC: 2
}
const POPULATE_CUSTOMER = { path: "customer", select: "" }
const POPULATE_PLAYER = { path: "player", select: "" }
const POPULATE_MESSAGE = { path: "latestMessage", select: "" }
const POPULATE_HIRE = { path: "latestHire", select: "" }

const SUCCESS_CODES = {
    CREATE_CONVERSATION_SUCCESS: "CREATE_CONVERSATION_SUCCESS",
    CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
    UPLOAD_IMAGES_CHAT_SUCCESS: "UPLOAD_IMAGES_CHAT_SUCCESS",
    GET_CONVERSATIONS_SUCCESS: "GET_CONVERSATIONS_SUCCESS",
    READER_MESSAGES_SUCCESS: "READER_MESSAGES_SUCCESS",
    CREATE_COMPLAIN_SUCCESS: "CREATE_COMPLAIN_SUCCESS",
    GET_DETAIL_CONVERSATION_SUCCESS: "GET_DETAIL_CONVERSATION_SUCCESS",
    DELETE_CONVERSATION_SUCCESS: "DELETE_CONVERSATION_SUCCESS",
    UPDATE_CONVERSATION_SUCCESS: "UPDATE_CONVERSATION_SUCCESS"
}

const ERROR_CODES = {
    ERROR_CONVERSATION_NOT_FOUND: "ERROR_CONVERSATION_NOT_FOUND",
    ERROR_SENDER_NOT_FOUND: "ERROR_SENDER_NOT_FOUND",
    ERROR_SENDER_NOT_IN_CONVERSATION: "ERROR_SENDER_NOT_IN_CONVERSATION",
    ERROR_BODY_INVALID: "ERROR_BODY_INVALID",
    ERROR_USER_NOT_IN_CONVERSATION: "ERROR_USER_NOT_IN_CONVERSATION",
    ERROR_MEMBERS_NOT_FOUND: "ERROR_MEMBERS_NOT_FOUND",
    ERROR_MESSAGE_NOT_FOUND: "ERROR_MESSAGE_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND",
    ERROR_HIRE_NOT_COMPLAIN: "ERROR_HIRE_NOT_COMPLAIN"
}

export default {
    POPULATE_HIRE,
    TYPES,
    STATUS,
    SUCCESS_CODES,
    ERROR_CODES,
    POPULATE_CUSTOMER,
    POPULATE_PLAYER,
    POPULATE_MESSAGE
}
