const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}
const TYPES = {
    TEXT: 1,
    MEDIA: 2
}
const POPULATE_FROM_USER = { path: "fromUser" }
const POPULATE_TO_USER = { path: "toUser" }

const SUCCESS_CODES = {
    CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    GET_DETAIL_MESSAGE_SUCCESS: "GET_DETAIL_MESSAGE_SUCCESS",
    DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    CREATE_DONATE_SUCCESS: "CREATE_DONATE_SUCCESS"
}

const ERROR_CODES = {
    ERROR_MESSAGE_NOT_FOUND: "ERROR_MESSAGE_NOT_FOUND",
    ERROR_CONVERSATION_NOT_FOUND: "ERROR_CONVERSATION_NOT_FOUND",
    ERROR_SENDER_NOT_FOUND: "ERROR_SENDER_NOT_FOUND",
    ERROR_TO_USER_NOT_FOUND: "ERROR_TO_USER_NOT_FOUND",
    ERROR_USER_NOT_ENOUGH_MONEY: "ERROR_USER_NOT_ENOUGH_MONEY"
}

export default { POPULATE_FROM_USER, POPULATE_TO_USER, STATUS, SUCCESS_CODES, ERROR_CODES, TYPES }
