const ERROR_CODES = {
    ERROR_UNAUTHORIZED: "ERROR_UNAUTHORIZED",
    ERROR_TOKEN_INVALID: "ERROR_TOKEN_INVALID",
    ERROR_FORBIDDEN: "ERROR_FORBIDDEN",
    ERROR_OTP_EXPIRED: "ERROR_OTP_EXPIRED",
    ERROR_OTP_INVALID: "ERROR_OTP_INVALID",
    ERROR_SEND_MAIL: "ERROR_SEND_MAIL",
    ERROR_KEY_UPLOAD_INVALID: "ERROR_KEY_UPLOAD_INVALID",
    ERROR_MIMETYPE_INVALID: "ERROR_MIMETYPE_INVALID"
}

const SKIP_DEFAULT = 0
const LIMIT_DEFAULT = 100

export { ERROR_CODES, SKIP_DEFAULT, LIMIT_DEFAULT }
