const ERROR_CODES = {
    ERROR_UNAUTHORIZED: "ERROR_UNAUTHORIZED",
    ERROR_TOKEN_INVALID: "ERROR_TOKEN_INVALID",
    ERROR_FORBIDDEN: "ERROR_FORBIDDEN",
    ERROR_OTP_EXPIRED: "ERROR_OTP_EXPIRED",
    ERROR_OTP_INVALID: "ERROR_OTP_INVALID",
    ERROR_SEND_MAIL: "ERROR_SEND_MAIL",
    ERROR_KEY_UPLOAD_INVALID: "ERROR_KEY_UPLOAD_INVALID",
    ERROR_MIMETYPE_INVALID: "ERROR_MIMETYPE_INVALID",
    ERROR_SIZE_FILE_TOO_LARGE: "ERROR_SIZE_FILE_TOO_LARGE",
    ERROR_METHOD_INVALID: "ERROR_METHOD_INVALID",
    ERROR_HOST_INVALID: "ERROR_HOST_INVALID",
    ERROR_FILE_NOT_FOUND: "ERROR_FILE_NOT_FOUND"
}

const SKIP_DEFAULT = 0
const LIMIT_DEFAULT = 100
const TIME_ZONE = "Asia/Ho_Chi_Minh"
const SYSTEM_FEE = 5
const QUALITY = 30

export { ERROR_CODES, SKIP_DEFAULT, LIMIT_DEFAULT, TIME_ZONE, SYSTEM_FEE, QUALITY }
