const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}
const TYPES = {
    TEXT: 1,
    MEDIA: 2
}
const HIRE_STEPS = {
    WAITING: 1,
    ACCEPT: 2,
    PLAYER_CANCEL: 3,
    CUSTOMER_CANCEL: 4,
    COMPLETE: 5
}
const POPULATE_OPTIONS = { path: "sender" }
const POPULATE_CUSTOMER = { path: "customer" }
const POPULATE_PLAYER = { path: "player" }

const SUCCESS_CODES = {
    CREATE_HIRE_SUCCESS: "CREATE_HIRE_SUCCESS",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    GET_DETAIL_HIRE_SUCCESS: "GET_DETAIL_HIRE_SUCCESS",
    DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    UPDATE_MESSAGE_SUCCESS: "UPDATE_MESSAGE_SUCCESS"
}

const ERROR_CODES = {
    ERROR_HIRE_NOT_FOUND: "ERROR_HIRE_NOT_FOUND",
    ERROR_PLAYER_ID_INVALID: "ERROR_PLAYER_ID_INVALID",
    ERROR_CUSTOMER_ID_INVALID: "ERROR_CUSTOMER_ID_INVALID",
    ERROR_SENDER_NOT_FOUND: "ERROR_SENDER_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND"
}

export default {
    HIRE_STEPS,
    POPULATE_CUSTOMER,
    POPULATE_PLAYER,
    STATUS,
    SUCCESS_CODES,
    ERROR_CODES,
    POPULATE_OPTIONS,
    TYPES
}
