const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}
const TYPES = {
    TEXT: 1,
    MEDIA: 2
}
const POPULATE_OPTIONS = { path: "sender" }

const SUCCESS_CODES = {
    CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    GET_DETAIL_MESSAGE_SUCCESS: "GET_DETAIL_MESSAGE_SUCCESS",
    DELETE_MESSAGE_SUCCESS: "DELETE_MESSAGE_SUCCESS",
    UPDATE_MESSAGE_SUCCESS: "UPDATE_MESSAGE_SUCCESS"
}

const ERROR_CODES = {
    ERROR_MESSAGE_NOT_FOUND: "ERROR_MESSAGE_NOT_FOUND",
    ERROR_CONVERSATION_NOT_FOUND: "ERROR_CONVERSATION_NOT_FOUND",
    ERROR_SENDER_NOT_FOUND: "ERROR_SENDER_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND"
}

export default { STATUS, SUCCESS_CODES, ERROR_CODES, POPULATE_OPTIONS, TYPES }
