const STATUS_HIRE = {
    READY: 1,
    BUSY: 2
}

const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}

const TYPES = {
    VIP: 1,
    HOT: 2,
    NEW: 3
}

const SUCCESS_CODES = {
    GET_PLAYER_INFO_SUCCESS: "GET_PLAYER_INFO_SUCCESS",
    GET_DETAIL_PLAYER_INFO_SUCCESS: "GET_DETAIL_PLAYER_INFO_SUCCESS",
    GET_STATISTICS_PLAYER_SUCCESS: "GET_STATISTICS_PLAYER_SUCCESS",
    GET_STATISTIC_CONDITIONS_SUCCESS: "GET_STATISTIC_CONDITIONS_SUCCESS",
    CREATE_PLAYER_INFO_SUCCESS: "CREATE_PLAYER_INFO_SUCCESS",
    UPDATE_PLAYER_INFO_SUCCESS: "UPDATE_PLAYER_INFO_SUCCESS",
    UPDATE_HIRE_SETTINGS_SUCCESS: "UPDATE_HIRE_SETTINGS_SUCCESS",
    CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
    GET_REVIEW_SUCCESS: "GET_REVIEW_SUCCESS",
    UPDATE_REVIEW_SUCCESS: "UPDATE_REVIEW_SUCCESS",
    UPLOAD_IMAGES_SUCCESS: "UPLOAD_IMAGES_SUCCESS",
    UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
    REMOVE_IMAGES_SUCCESS: "REMOVE_IMAGES_SUCCESS"
}

const ERROR_CODES = {
    ERROR_PLAYER_NOT_FOUND: "ERROR_PLAYER_NOT_FOUND",
    ERROR_ONLY_UPLOAD_FIFTEEN_IMAGES: "ERROR_ONLY_UPLOAD_FIFTEEN_IMAGES",
    ERROR_REVIEW_NOT_FOUND: "ERROR_REVIEW_NOT_FOUND",
    ERROR_USER_ALREADY_CREATE_PLAYER_INFO: "ERROR_USER_ALREADY_CREATE_PLAYER_INFO",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND"
}

const PLAYER_CONDITIONS = {
    HOT_PLAYER: {
        incomeMin7Day: 200,
        countRate: 5,
        avgRate: 4,
        ratioComplete: 0.5
    },
    VIP_PLAYER: {
        incomeMin7Day: 500,
        countRate: 10,
        avgRate: 4.5,
        ratioComplete: 0.8
    }
}

export default { STATUS_HIRE, STATUS, SUCCESS_CODES, ERROR_CODES, TYPES, PLAYER_CONDITIONS }
