const STATUS = {
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE"
}
const OPERATIONS = {
    PLUS: "+",
    SUBTRACT: "-"
}
const METHODS = {
    PAYPAL: "PAYPAL",
    CREDIT_CARD: "CREDIT_CARD",
    RAZOR_PAY: "RAZOR_PAY",
    GOOGLE_PAY: "GOOGLE_PAY",
    APPLE_PAY: "APPLE_PAY"
}
// PayPal, Credit Card (Stripe), RazorPay, Google Pay, Apple Pa
const SUCCESS_CODES = {
    CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
    RECHARGE_SUCCESS: "RECHARGE_SUCCESS",
    GET_REVIEWS_SUCCESS: "GET_REVIEWS_SUCCESS",
    GET_DETAIL_REVIEW_SUCCESS: "GET_DETAIL_REVIEW_SUCCESS",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    UPDATE_REVIEW_SUCCESS: "UPDATE_REVIEW_SUCCESS"
}

const ERROR_CODES = {
    ERROR_REVIEW_NOT_FOUND: "ERROR_REVIEW_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND",
    CREATE_PAYMENT_STRIPE_FAIL: "CREATE_PAYMENT_STRIPE_FAIL",
    CREATE_PAYMENT_RAZORPAY_FAIL: "CREATE_PAYMENT_RAZORPAY_FAIL",
    CREATE_PAYMENT_CUSTOMER_STRIPE_FAIL: "CREATE_PAYMENT_CUSTOMER_STRIPE_FAIL",
    CREATE_PAYMENT_METHOD_STRIPE_FAIL: "CREATE_PAYMENT_METHOD_STRIPE_FAIL",
    PAYMENT_METHOD_ID_REQUIRED: "PAYMENT_METHOD_ID_REQUIRED",
    ERROR_PAYMENT_METHOD_ID_NOT_FOUND: "ERROR_PAYMENT_METHOD_ID_NOT_FOUND",
    ERROR_CREDIT_CARD_CONFIG_NOT_CREATE: "ERROR_CREDIT_CARD_CONFIG_NOT_CREATE",
    ERROR_RECHARGE_PAYPAL_FAIL: "ERROR_RECHARGE_PAYPAL_FAIL",
    ERROR_AMOUNT_INVALID: "ERROR_AMOUNT_INVALID"
}

export default { STATUS, SUCCESS_CODES, ERROR_CODES, METHODS, OPERATIONS }
