const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2
}

const SUCCESS_CODES = {
    CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
    GET_REVIEWS_SUCCESS: "GET_REVIEWS_SUCCESS",
    GET_DETAIL_REVIEW_SUCCESS: "GET_DETAIL_REVIEW_SUCCESS",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    UPDATE_REVIEW_SUCCESS: "UPDATE_REVIEW_SUCCESS"
}

const ERROR_CODES = {
    ERROR_REVIEW_NOT_FOUND: "ERROR_REVIEW_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND"
}

export default { STATUS, SUCCESS_CODES, ERROR_CODES }
