const METHOD = {
    PAYPAL: 1,
    BANK: 2
}

const STATUS = {
    PROCESSING: 1,
    SUCCESS: 2,
    CANCELED: 3
}
const COLLECTION_PAYMENT_SETTINGS = "payment_settings"

const ERROR_CODES = {
    ERROR_CREATE_PAYMENT_PAYPAL_FAIL: "ERROR_CREATE_PAYMENT_PAYPAL_FAIL",
    ERROR_EXECUTE_PAYMENT_PAYPAL_FAIL: "ERROR_EXECUTE_PAYMENT_PAYPAL_FAIL",
    ERROR_GET_PAYMENT_PAYPAL_FAIL: "ERROR_GET_PAYMENT_PAYPAL_FAIL"
}

const SUCCESS_CODES = {
    GET_PAYMENT_SETTING_SUCCESS: "GET_PAYMENT_SETTING_SUCCESS",
    CREATE_PAYMENT_SETTING_SUCCESS: "CREATE_PAYMENT_SETTING_SUCCESS",
    UPDATE_PAYMENT_SETTING_SUCCESS: "UPDATE_PAYMENT_SETTING_SUCCESS"
}

export default { METHOD, STATUS, ERROR_CODES, SUCCESS_CODES, COLLECTION_PAYMENT_SETTINGS }
