const TYPES = {
    FACEBOOK: "facebook",
    EMAIL: "email",
    PHONE: "phone",
    NORMAL: "normal"
}

const STATUS = {
    ACTIVE: 1,
    INACTIVE: 2,
    VERIFIED: 3
}

const ROLES = {
    ADMIN: 1,
    NORMAL: 2
}

const GENDER = {
    MALE: 1,
    FEMALE: 2
}

const ERROR_CODES = {
    ERROR_USER_NOT_FOUND: "ERROR_USER_NOT_FOUND",
    ERROR_UNAUTHORIZED: "ERROR_INCORRECT_EMAIL_OR_PASSWORD",
    ERROR_EMAIL_ALREADY_EXISTS: "ERROR_EMAIL_ALREADY_EXISTS",
    ERROR_PASSWORD_INVALID: "ERROR_PASSWORD_INVALID",
    ERROR_EMAIL_IS_REQUIRED: "ERROR_EMAIL_IS_REQUIRED",
    ERROR_EMAIL_DOES_NOT_EXIST: "ERROR_EMAIL_DOES_NOT_EXIST",
    ERROR_INVALID_OR_EXPIRED_PASSWORD_RESET_TOKEN: "ERROR_INVALID_OR_EXPIRED_PASSWORD_RESET_TOKEN"
}

const SUCCESS_CODES = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
    SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    REQUEST_RESET_PASSWORD_SUCCESS: "REQUEST_RESET_PASSWORD_SUCCESS"
}

export { TYPES, STATUS, ROLES, GENDER, ERROR_CODES, SUCCESS_CODES }
