const STATUS = {
    COMPLETED: "COMPLETED",
    CANCELED: "CANCELED",
    FAILED: "FAILED"
}
const WITHDRAW_PAYPAL_BATCH_STATUS = {
    DENIED: "DENIED",
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    CANCELED: "CANCELED",
    FAILED: "FAILED"
}

const TRANSACTION_STATUS = {
    SUCCESS: "SUCCESS",
    UNCLAIMED: "UNCLAIMED",
    FAILED: "FAILED",
    PENDING: "PENDING",
    ONHOLD: "ONHOLD",
    RETURNED: "RETURNED",
    BLOCKED: "BLOCKED",
    REFUNDED: "REFUNDED",
    REVERSED: "REVERSED"
}

const METHODS = {
    PAYPAL: "PAYPAL"
}

const PAYOUT_FEE = 0.5

const SUCCESS_CODES = {
    CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
    GET_REVIEWS_SUCCESS: "GET_REVIEWS_SUCCESS",
    GET_DETAIL_REVIEW_SUCCESS: "GET_DETAIL_REVIEW_SUCCESS",
    DELETE_REVIEW_SUCCESS: "DELETE_REVIEW_SUCCESS",
    UPDATE_REVIEW_SUCCESS: "UPDATE_REVIEW_SUCCESS",
    WITHDRAW_PAYPAL_SUCCESS: "WITHDRAW_PAYPAL_SUCCESS",
    GET_WITHDRAW_FEES_SUCCESS: "GET_WITHDRAW_FEES_SUCCESS",
    GET_WITHDRAWS_SUCCESS: "GET_WITHDRAWS_SUCCESS"
}

const ERROR_CODES = {
    ERROR_REVIEW_NOT_FOUND: "ERROR_REVIEW_NOT_FOUND",
    ERROR_USER_REVIEWER_NOT_FOUND: "ERROR_USER_REVIEWER_NOT_FOUND",
    ERROR_USER_RECEIVER_NOT_FOUND: "ERROR_USER_RECEIVER_NOT_FOUND",
    ERROR_ONLY_CUSTOMER_CREATE_REVIEW: "ERROR_ONLY_CUSTOMER_CREATE_REVIEW",
    ERROR_CUSTOMER_ALREADY_REVIEW_THIS_HIRE: "ERROR_CUSTOMER_ALREADY_REVIEW_THIS_HIRE",
    ERROR_HIRE_NOT_COMPLETE: "ERROR_HIRE_NOT_COMPLETE",
    ERROR_PAYOUT_PAYPAL_NOT_FOUND: "ERROR_PAYOUT_PAYPAL_NOT_FOUND",
    ERROR_PAYOUT_PAYPAL_FAIL: "ERROR_PAYOUT_PAYPAL_FAIL",
    ERROR_EMAIL_INVALID: "ERROR_EMAIL_INVALID",
    ERROR_WITHDRAW_PAYPAL_FAIL: "ERROR_WITHDRAW_PAYPAL_FAIL",
    ERROR_USER_NOT_ENOUGH_MONEY: "ERROR_USER_NOT_ENOUGH_MONEY"
}

export default {
    PAYOUT_FEE,
    TRANSACTION_STATUS,
    STATUS,
    SUCCESS_CODES,
    ERROR_CODES,
    WITHDRAW_PAYPAL_BATCH_STATUS,
    METHODS
}
